"""Add user_agent column to api_logs

Revision ID: cb5219bd691c
Revises: 574862549069
Create Date: 2026-02-01 22:47:01.818326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb5219bd691c'
down_revision: Union[str, None] = '574862549069'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_logs', sa.Column('user_agent', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_logs', 'user_agent')
    # ### end Alembic commands ###
